name:                PORR-thread
version:             0.1.0.0
github:              "githubuser/PORR-thread"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/PORR-thread#readme>

default-extensions:
- ScopedTypeVariables
dependencies:
- base >= 4.7 && < 5
- deepseq
- either
- multilinear
- multilinear-io
- parallel
- transformers
ghc-options:
- -O2
- -W

library:
  source-dirs: src

benchmarks:
  mnist-sequential-bench:
    main:                Bench.hs
    source-dirs:         benchmark/mnist-sequential
    dependencies:
    - criterion
    - PORR-thread
  mnist-multicore-bench:
    main:                Bench.hs
    source-dirs:         benchmark/mnist-multicore
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - PORR-thread
  mnist-2-cores-bench:
    main:                Bench.hs
    source-dirs:         benchmark/mnist-2-cores
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    dependencies:
    - criterion
    - PORR-thread
  mnist-3-cores-bench:
    main:                Bench.hs
    source-dirs:         benchmark/mnist-3-cores
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N3
    dependencies:
    - criterion
    - PORR-thread
  mnist-gpu-bench:
    main:                Bench.hs
    source-dirs:         benchmark/mnist-gpu
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - PORR-thread

executables:
  mnist-sequential:
    main:                Main.hs
    source-dirs:         app/mnist-sequential
    dependencies:
    - PORR-thread
  mnist-multicore:
    main:                Main.hs
    source-dirs:         app/mnist-multicore
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PORR-thread
  mnist-2-cores:
    main:                Main.hs
    source-dirs:         app/mnist-2-cores
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    dependencies:
    - PORR-thread
  mnist-3-cores:
    main:                Main.hs
    source-dirs:         app/mnist-3-cores
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N3
    dependencies:
    - PORR-thread
  mnist-gpu:
    main:                Main.hs
    source-dirs:         app/mnist-gpu
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PORR-thread

tests:
  PORR-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PORR-thread
